file-upload/file-upload/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', lambda x: HttpResponseRedirect('/upload/')),
    url(r'^upload/', include('fileupload.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file-upload/fileupload/urls.py
from django.conf.urls import url
from fileupload.views import (
        #BasicPlusVersionCreateView,
        EkFileCreateView, EkFileDeleteView, EkFileListView,
        )
from . import views

app_name='fileupload'
urlpatterns = [
    #url(r'^basic/plus/$', BasicPlusVersionCreateView.as_view(), name='upload-basic-plus'),
    url(r'^new/$', EkFileCreateView.as_view(), name='upload-new'),
    url(r'^delete/(?P<pk>\d+)$', EkFileDeleteView.as_view(), name='upload-delete'),
    url(r'^view/$', EkFileListView.as_view(), name='upload-view'),
    url(r'^$',views.index,name='index'),
    url(r'^verify$',views.verify,name='verify'),
    url(r'^transfer/$', views.transfer, name="transfer"),
]

file-upload/fileupload/models.py
from django.db import models


class EkFile(models.Model):
    file = models.FileField(upload_to="pictures")
    slug = models.SlugField(max_length=50, blank=True)

    def __str__(self):
        return self.file.name

    @models.permalink
    def get_absolute_url(self):
        return ('upload-new', )

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(EkFile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.file.delete(False)
        super(EkFile, self).delete(*args, **kwargs)

file-upload/fileupload/views.py
import json
import logging

from .USBFinder import attemptMount,transfer_file
from hashlib import sha1
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.views.generic import CreateView, DeleteView, ListView
from .models import EkFile
from django.contrib.auth.models import User
from .response import JSONResponse, response_mimetype
from .serialize import serialize
from django.urls import reverse

def index(request):
    return render(request,'fileupload/LOGIN.html')

def verify(request):
    user=User.objects.get(username=request.POST['email'])
    logger = logging.getLogger(__name__)
    password=request.POST['password']
    #_,salt,hashpw=user.password.split('$')
    logger.error(request.POST['email']+","+request.POST['password']+" \n next line")
    logger.error(user.password+", username is "+user.username)
    if(user is not None and user.check_password(password)):
        return HttpResponseRedirect('new/')
    else:
        return render(request,'fileupload/LOGIN.html',{'invalid':'not a valid username or password'})
        
    
    
    
class EkFileCreateView(CreateView):
    model = EkFile
    fields = "__all__"

    def form_valid(self, form):
    	
        self.object = form.save()
        print self.object
        files = [serialize(self.object)]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        print 'Before you send post request'
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
        return HttpResponse(content=data, status=400, content_type='application/json')


#class BasicPlusVersionCreateView(EkFileCreateView):
 #   template_name_suffix = '_basicplus_form'


class EkFileDeleteView(DeleteView):
    model = EkFile

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        response = JSONResponse(True, mimetype=response_mimetype(request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response


class EkFileListView(ListView):
    model = EkFile
    
    def render_to_response(self, context, **response_kwargs):
        files = [ serialize(p) for p in self.get_queryset() ]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response
    
def transfer(request):
    files=[]
    #Returns list of files that correspond to requirements
    files=attemptMount()
    files_existing=[]
    unique_files_existing=[]
    unique_files=[]
    if files is not None:
        unique_files  = [file for file in files if file not in files_existing_names]
    else:
        unique_files = None
    total_done = 0
    if unique_files is not None:
        for file1 in unique_files:
            if file1 != 'content.json':
                try:
                    x =  File.objects.get(file_link=file)
                except File.DoesNotExist:
                    x = None
                if x == None:

                    fModel = EkFile(file = file1)
                    fModel.save()
                    unique_files_existing.append(fModel)
    files_existing.append(unique_files_existing)
    files_existing_names.append(unique_files)
    if request.method == 'GET':
            unique_files_existing
            total_amount = len(files)
            download_more = True
            fileCount = request.POST.get("file_descriptor", "")
            try:
                return_code = transfer_file(files[int(fileCount)])
                if return_code != 0:
                    print ('USB unexpectedly removed!')
                    return HttpResponse(content=data, status=400, content_type='application/json')
            except IndexError as error:											#Thrown when there are no more files to #download 
                download_more = None
            total_done += 1
            percentage_done = int(total_done*100/total_amount)
            template = loader.get_template('checkUpdates/downloadFiles.html')
            context = {
            'files_existing' : unique_files_existing,
            'show_output' : download_more,
            'percentage_done' : percentage_done,
            'current_count'	: total_done,
            'btn_check_flag' : 'disabled',
            'download_more' : download_more,
            }
            return HttpResponseRedirect('new/')
    return HttpResponse("Please access this URL properly")
    

file-upload/fileupload/templates/fileupload/LOGIN.html
<!DOCTYPE HTML>
<html>
<head>
<title>File Upload Login</title>
<link rel="stylesheet" href="../static/css/login.css">
<!img src="images.jpg" style="width:200px;right:200px;height:228px;margin:10px;">
</head>
<body>
<div class="login-page">
       <form  class="form" action="{% url 'fileupload:verify' %}" method="post">
    {%csrf_token%}
     {% if invalid %}
           <p>{{invalid}}</p>
     {% endif %}
      <input type="text" id="email" name="email" placeholder="username">
      <br>
      <input type="password" id="password" name="password" placeholder="password">
      <br>
     <Button type="submit">Login</Button>
    </form>
</div>
</body>
</html>

file-upload/fileupload/templates/fileupload/ekfile_form.html
{% extends "upload_base.html" %}
{% load upload_tags %}

{% block content %}
<div class="container">
    <h1 id="h">File Upload</h1>
    <br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
        
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="file" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="button" class="btn btn-primay start" id="usb">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>USB upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The loading indicator is shown during file processing -->
                <span class="fileupload-loading"></span>
            </div>
            <!-- The global progress information -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </form>
    <br>
    
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
{% upload_js %}


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="/static/js/ajax-utils.js"></script>
<script src="/static/js/scripts.js"></script>

<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/static/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/static/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="/static/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/static/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/static/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/static/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/static/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="/static/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="/static/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="/static/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/static/js/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="/static/js/main.js"></script>
<script src="/static/js/locale.js"></script>
<script src="/static/js/csrf.js"></script>
{% endblock %}

file-upload/fileupload/templates/upload_base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <!-- Force latest IE rendering engine or ChromeFrame if installed -->
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <meta charset="utf-8">
    <title>file upload</title>
    <meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bars, validation and preview images, audio and video for jQuery. Supports cross-domain, chunked and resumable file uploads and client-side image resizing. Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <!-- Generic page styles -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="/static/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="/static/css/jquery.fileupload-ui.css">
    <!-- CSS adjustments for browsers with JavaScript disabled -->
    <noscript><link rel="stylesheet" href="/static/css/jquery.fileupload-ui-noscript.css"></noscript>
    
    <!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
{% block content %}
    <h1>No content set</h1>
{% endblock %}

</body> 
</html>